version: '3.8'

services:
  web:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_BASE_URL: https://capitalspmta.up.railway.app
      JWT_SECRET: ${JWT_SECRET}
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      MP_NOTIFICATION_URL: https://capitalspmta.up.railway.app/api/payments/mercadopago/webhook
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: "587"
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: "Capital SP <cronosMTA@gmail.com>"
      STORE_API_TOKEN: ${STORE_API_TOKEN}
      MTA_API_TOKEN: ${MTA_API_TOKEN}
    command: sh -c "npx prisma generate && npx prisma db push && npm run db:seed && npm run start"

  worker:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    command: sh -c "npx prisma generate && npx prisma db push && npm run worker"
